name: CI/CD Pipeline for Shuup

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libjpeg-dev zlib1g-dev libfreetype6-dev libtiff-dev libwebp-dev \
            libffi-dev libssl-dev libpangocairo-1.0-0 \
            python3-dev gcc build-essential curl

          # Установка Rust (для сборки зависимостей с C/Rust)
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source $HOME/.cargo/env

      - name: Install Python dependencies (from Dockerfile logic)
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --use-pep517 -e.
          pip install -r requirements-tests.txt
          pip install markupsafe==2.0.1
          pip install django-prometheus

      - name: Set environment variables
        run: echo "DJANGO_SETTINGS_MODULE=shuup_workbench.settings.base_settings" >> $GITHUB_ENV

      - name: Build resources (optional)
        run: |
          python setup.py build_resources || true

      - name: Run tests
        run: |
          pytest shuup_tests/

      - name: Build Docker image
        run: |
          echo "Building Docker image for Shuup project..."
          docker build -t shuup-sample:latest .

      - name: Deploy step (simulated)
        run: |
          echo "Running docker container locally"
          echo "No remote server available, skipping actual deployment."
