name: CI/CD Pipeline for Shuup

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libjpeg-dev zlib1g-dev libfreetype6-dev libtiff-dev libwebp-dev \
          libxml2-dev libxslt1-dev  # Добавлены зависимости для lxml

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel pytest
        pip install django shuup  # Установка Django и Shuup
        # Если есть requirements.txt, можно использовать:
        # pip install -r requirements.txt

    - name: Set up Django settings
      run: |
        echo "DJANGO_SETTINGS_MODULE=shuup_tests.settings" >> $GITHUB_ENV
      # Замените shuup_tests.settings на правильный путь к вашему модулю настроек

    - name: Run tests
      run: |
        pytest shuup_tests/ --verbose

    - name: Build Docker image
      run: |
        echo "Building Docker image for Shuup project..."
        docker build -t shuup-sample:latest .

    - name: Deploy step (simulated)
      run: |
        echo "Running docker container locally"
        echo "No remote server available, skipping actual deployment."
